// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR882gPfn-pfg-J5LLb6KVNvgL5-7fDvI',
    appId: '1:110465701887:web:78f676837605fabc7179ca',
    messagingSenderId: '110465701887',
    projectId: 'todo-app-d38b7',
    authDomain: 'todo-app-d38b7.firebaseapp.com',
    storageBucket: 'todo-app-d38b7.appspot.com',
    measurementId: 'G-GP130PFT2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLPOfuNwaLcDIoEtilsNdysrw80NoZq6U',
    appId: '1:110465701887:android:dd6b567b10868d197179ca',
    messagingSenderId: '110465701887',
    projectId: 'todo-app-d38b7',
    storageBucket: 'todo-app-d38b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ENph5gzY5USNNEZSwEJnzVmhBI1W1jY',
    appId: '1:110465701887:ios:e6ecaae9c6595dc27179ca',
    messagingSenderId: '110465701887',
    projectId: 'todo-app-d38b7',
    storageBucket: 'todo-app-d38b7.appspot.com',
    iosClientId: '110465701887-vqhpvjpi8ha9t6575p4si2pm77ir0sii.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ENph5gzY5USNNEZSwEJnzVmhBI1W1jY',
    appId: '1:110465701887:ios:a83234a57b384cc47179ca',
    messagingSenderId: '110465701887',
    projectId: 'todo-app-d38b7',
    storageBucket: 'todo-app-d38b7.appspot.com',
    iosClientId: '110465701887-eaqdmnpum4g2bepmq4uace6nqk8crn3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
