// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBowNyFUgOZ9lzcki9uvWfMex3XYnBDsaY',
    appId: '1:258905811279:web:7026fa9a0e6498712d3d3a',
    messagingSenderId: '258905811279',
    projectId: 'fluttertestapp3-8102e',
    authDomain: 'fluttertestapp3-8102e.firebaseapp.com',
    storageBucket: 'fluttertestapp3-8102e.appspot.com',
    measurementId: 'G-LRTBLR5VRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuZM6zaJE2k-W0vf_y0Oj1rYuAFVQTP4Y',
    appId: '1:258905811279:android:04907d3985ee63062d3d3a',
    messagingSenderId: '258905811279',
    projectId: 'fluttertestapp3-8102e',
    storageBucket: 'fluttertestapp3-8102e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCal8EnEsbrK4QWOERF3rZnsCM9sen4NoU',
    appId: '1:258905811279:ios:8d24fdd0b80ccf712d3d3a',
    messagingSenderId: '258905811279',
    projectId: 'fluttertestapp3-8102e',
    storageBucket: 'fluttertestapp3-8102e.appspot.com',
    iosClientId: '258905811279-mhpjslrqqvh85ng3c4ngqbui960v144m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCal8EnEsbrK4QWOERF3rZnsCM9sen4NoU',
    appId: '1:258905811279:ios:6f0dc996375164c52d3d3a',
    messagingSenderId: '258905811279',
    projectId: 'fluttertestapp3-8102e',
    storageBucket: 'fluttertestapp3-8102e.appspot.com',
    iosClientId: '258905811279-mk4d5he6gfn5v33mlm93gn5rtq4e43va.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestApp3.RunnerTests',
  );
}
